#ifndef CUSTOM_DEBUG_DRAW_INCLUDE
#define CUSTOM_DEBUG_DRAW_INCLUDE

#define DEBUG_DRAW_MODE_ALBEDO (1)
#define DEBUG_DRAW_MODE_NORMAL_WORLD (2)
#define DEBUG_DRAW_MODE_NORMAL_LOCAL (3)
#define DEBUG_DRAW_MODE_METALLIC (4)
#define DEBUG_DRAW_MODE_ROUGHNESS (5)
#define DEBUG_DRAW_MODE_EMISSION (6)
#define DEBUG_DRAW_MODE_LIGHTDIFFUSE (7)
#define DEBUG_DRAW_MODE_LIGHTSPECULAR (8)
#define DEBUG_DRAW_MODE_GIDIFFUSE (9)
#define DEBUG_DRAW_MODE_GISPECULAR (10)
#define DEBUG_DRAW_MODE_AO (11)
#define DEBUG_DRAW_MODE_SHADOW (12)

int _DebugDrawType;

#endif